project:
  type: website
  output-dir: docs

website:
  title: "Hui Yao"
  site-url: "https://HuiYao-Amber.github.io/biostat777-intro-Hui-Yao"
  repo-url: "https://github.com/HuiYao-Amber/biostat777-intro-Hui-Yao"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Example analysis"
        href: example-analysis.qmd

format:
  html:
    theme: cosmo
    toc: true